import { useAppContext } from "../../context/AppContext";

export function DashboardPage() {
  const { currentUser, documents, modelCatalog, stats, users } = useAppContext();

  return (
    <div className="admin-content">
      <section className="dashboard-hero">
        <div>
          <span className="hero-pill">Operations</span>
          <h2>Admin runtime overview</h2>
          <p>Track the current state of the knowledge base, model runtime, user roles, and agent activity.</p>
        </div>
      </section>

      <section className="metric-grid">
        <article className="metric-card">
          <span>Knowledge docs</span>
          <strong>{stats?.documents ?? 0}</strong>
          <small>Total documents stored in the knowledge base.</small>
        </article>
        <article className="metric-card">
          <span>Indexed chunks</span>
          <strong>{stats?.indexed_chunks ?? 0}</strong>
          <small>Chunks currently searchable by the retrieval layer.</small>
        </article>
        <article className="metric-card">
          <span>Conversations</span>
          <strong>{stats?.conversations ?? 0}</strong>
          <small>Threads owned by the signed-in account.</small>
        </article>
        <article className="metric-card">
          <span>Tasks</span>
          <strong>{stats?.tasks ?? 0}</strong>
          <small>Agent execution records generated by this account.</small>
        </article>
      </section>

      <section className="admin-grid two-columns">
        <article className="panel-card">
          <div className="panel-head">
            <div>
              <span className="panel-kicker">Knowledge Snapshot</span>
              <h3>Recent documents</h3>
            </div>
          </div>
          <div className="chunk-list">
            {documents.slice(0, 5).map((document) => (
              <article key={document.id} className="chunk-card">
                <strong>{document.title}</strong>
                <p>
                  {document.department} / {document.chunk_count || 0} chunks
                </p>
              </article>
            ))}
          </div>
        </article>

        <article className="panel-card">
          <div className="panel-head">
            <div>
              <span className="panel-kicker">Runtime</span>
              <h3>Current session</h3>
            </div>
          </div>
          <div className="definition-list">
            <div>
              <span>Signed-in user</span>
              <strong>{currentUser?.name || "-"}</strong>
            </div>
            <div>
              <span>Users</span>
              <strong>{users.length}</strong>
            </div>
            <div>
              <span>Model provider</span>
              <strong>{stats?.llm_provider || "-"}</strong>
            </div>
            <div>
              <span>Active model</span>
              <strong>{modelCatalog?.active_model || stats?.llm_model || "-"}</strong>
            </div>
          </div>
        </article>
      </section>
    </div>
  );
}
